# Generated by Django 3.2.3 on 2021-05-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0002_auto_20210522_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_date',
        ),
    ]
