# Generated by Django 3.2.3 on 2021-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0004_customer_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
