# Generated by Django 3.2.3 on 2021-05-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0005_alter_customer_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
    ]
