# Generated by Django 3.2.3 on 2021-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0006_remove_customer_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_all', models.IntegerField()),
                ('landing_page', models.TextField()),
                ('description', models.TextField()),
                ('UTP', models.TextField()),
                ('competitors', models.TextField()),
                ('terms', models.DurationField()),
                ('geography', models.TextField()),
                ('KPI', models.TextField()),
                ('audience', models.TextField()),
                ('suggestions', models.TextField()),
                ('companies_before', models.TextField()),
                ('who_prep_materials', models.TextField()),
                ('instrument', models.TextField()),
                ('official_list', models.TextField()),
                ('CRM', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
