# Generated by Django 3.2.3 on 2021-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0007_auto_20210527_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='terms',
            field=models.TextField(),
        ),
    ]
