# Generated by Django 3.2.3 on 2021-05-29 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0010_fileexel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileexel',
            name='title',
        ),
        migrations.AddField(
            model_name='fileexel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
